language: d
d:
  - dmd-2.073.2

addons:
  apt:
    packages:
    - libevent-dev
    - expect-dev
    - python3
    - python3-pip

install:
  - dub fetch doveralls

script:
  - pip3 install pyparsing
  - mkdir logs
  - dub test
  # TODO: Coverage
  # - rm .*.lst # hack for test coverage
  # - dub run doveralls
