language: d
d:
  - dmd

addons:
  apt:
    packages:
    - libevent-dev

install:
  - dub fetch doveralls

script:
  - dub build
  - dub test -b unittest-cov --build-mode=allAtOnce
  - rm .*.lst # hack for test coverage
  - dub run doveralls
