language: d
d:
  - dmd

addons:
  apt:
    packages:
    - libevent-dev

install:
  - dub fetch doveralls

script:
  - mkdir logs
  - dub test
  # TODO: Coverage
  # - rm .*.lst # hack for test coverage
  # - dub run doveralls
