language: d
d:
  - dmd

addons:
  apt:
    packages:
    - libevent-dev

install:
  - dub fetch doveralls

script:
  - dub test -b unittest-cov --combined --build-mode=allAtOnce --verbose
  - rm .*.lst # hack for test coverage
  - dub run doveralls
