language: d
d:
  - dmd-2.073.2

addons:
  apt:
    packages:
    - libevent-dev
    - expect-dev

install:
  - dub fetch doveralls

script:
  - mkdir logs
  - dub test
  # TODO: Coverage
  # - rm .*.lst # hack for test coverage
  # - dub run doveralls
